checks:
  php:
    code_rating: true
    duplication: true
tools:
  external_code_coverage: true
  php_code_coverage:
    test_command: "phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.clover"
    filter:
      paths: ["lib/*"]
    php_sim:
      enabled: true
      filter:
        paths: ["lib/*"]
    php_mess_detector:
      enabled: true
      filter:
        paths: ["lib/*"]
    php_pdepend:
      enabled: true
      filter:
        paths: ["lib/*"]
    php_analyzer:
      enabled: true
      filter:
        paths: ["lib/*"]
