checks:
  php:
    code_rating: true
    duplication: true
build:
  tests:
    override:
      -
        command: 'phpunit -t tests/phpunit.xml --coverage-clover=coverage/coverage.xml'
        coverage:
          file: 'coverage/coverage.xml'
          format: 'php-clover'
